### ISSUE TITLE
Problem executing git-p4 submit

### ISSUE THREAD

**Issue by ketjow** [ermshiperete/git-p4#19]
I have a problem setting up git with perforce using git-p4.
After finishing all the steps from this excellent blog post: http://owenou.com/2011/03/23/git-up-perforce-with-git-p4.html, I try to add a new file/modify an existing file in the local git repository. 

After committing the change to git and executing  
`git p4 submit --verbose`  
which should push the changes to the p4 repository, I get 65534 lines of output:

> Reading pipe: git notes --ref=git-p4 show HEAD~1  
> Reading pipe: git notes --ref=git-p4 show HEAD~2  
> [...]  
> Reading pipe: git notes --ref=git-p4 show HEAD~65534  
> Traceback (most recent call last):  
>   File "/home/wgorski/opt/git-p4/git-p4", line 2754, in <module>  
>     main()  
>   File "/home/wgorski/opt/git-p4/git-p4", line 2749, in main  
>     if not cmd.run(args):  
>   File "/home/wgorski/opt/git-p4/git-p4", line 1125, in run  
>     self.depotPath = settings['depot-paths'][0]  
> KeyError: 'depot-paths'  

Needless to say, the changes are not pushed to the p4 repository.

**Comment by ermshiperete** [comment]
The blog uses the git-p4 version from git/contrib. That version isn't compatible with this version (this version stores the info about the p4 changelist in notes, the version from git/contrib modifies the commit message). You can check by doing a git log (or git log --show-notes=git-p4). You'll see something like [depot-paths = "//depot/bla/": change = 38261] either in the commit message or under "Notes (git-p4)".

**Comment by ketjow** [comment]
The problem was an old git version, I used 1.7.0. Since git-p4 requires 1.7.1, this is not an issue.
