### ISSUE TITLE
bug with verbose mode, logging commits

### ISSUE THREAD

**Issue by dbiollo** [ermshiperete/git-p4#9]
Running "git p4 submit --verbose" fails on the logging.

Check out line 1128:
        if self.verbose:
            print "Commits to apply: " + self.commits

Doesn't seem to work since self.commits is an array. This code does work:
            print "Commits to apply: %s" % self.commits

**Comment by mwerle** [comment]
Thanks - I just came across the same issue and fixed it using a for loop but this is much more elegant.
